# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160625_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
    ]
